# visionfm 4 classes
nohup env CUDA_VISIBLE_DEVICES=0 python train_multiscale_uncertainty.py \
--result_root_path "./SLO_results/stdr_bode_250530" \
--result_name "icdr_visionfm_1344_4cls_myunc" \
--loss_type my_uncertainty \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 5 \
--finetune "/data_A/xujialiu/checkpoints/foundation_model_weights/my_VFM_Fundus_weights.pth" \
--data_path /data_A/xujialiu/datasets/UWF_datasets \
--csv_path "/data_A/xujialiu/datasets/UWF_datasets/250530_get_model_tabular_data/icdr4_other_250530.csv" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 2 \
--accum_iter 16 > ./SLO_results/stdr_bode_250530/icdr_visionfm_1344_4cls_myunc_`date +%Y%m%d_%H%M`.log 2>&1 &
