CUDA_VISIBLE_DEVICES=0 python train_multiscale_odin.py \
--eval \
--test_name "val" \
--result_root_path "./SLO_results/odin_250609" \
--result_name "in_distribution" \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 4 \
--data_path "/data_A/xujialiu/datasets/UWF_datasets" \
--loss_type "cross_entropy" \
--finetune "/data_A/xujialiu/projects/FMUE_SLO/SLO_results/stdr_bode_250510/stdr_bode_icdr_visionfm_1344_4cls_20250513_1814/checkpoints/checkpoint_38.pth" \
--csv_path "/data_A/xujialiu/datasets/UWF_datasets/tabular_data/stdr_bode_icdr_add_nv_prh_combine_01_250509.csv" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 1 \
--accum_iter 16

CUDA_VISIBLE_DEVICES=0 python train_multiscale_odin.py \
--eval \
--test_name "val" \
--result_root_path "./SLO_results/odin_250609" \
--result_name "other_diseases" \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 4 \
--data_path "/data_A/xujialiu/datasets/UWF_datasets" \
--loss_type "cross_entropy" \
--finetune "/data_A/xujialiu/projects/FMUE_SLO/SLO_results/stdr_bode_250510/stdr_bode_icdr_visionfm_1344_4cls_20250513_1814/checkpoints/checkpoint_38.pth" \
--csv_path "/data_A/xujialiu/datasets/bode/250530_get_model_tabular_data/icdr4_other_diseases_250530.csv" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 1 \
--accum_iter 16


CUDA_VISIBLE_DEVICES=0 python train_multiscale_odin.py \
--eval \
--result_root_path "./SLO_results/odin_250609" \
--result_name "japan_in" \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 4 \
--loss_type "cross_entropy" \
--finetune "/data_A/xujialiu/projects/FMUE_SLO/SLO_results/stdr_bode_250510/stdr_bode_icdr_visionfm_1344_4cls_20250513_1814/checkpoints/checkpoint_38.pth" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 1 \
--data_path "/data_A/xujialiu/datasets/UWF_external/Tsukazaki" \
--csv_path "/data_A/xujialiu/datasets/UWF_external/000000_prepare_external_validation/Tsukazaki.csv" \
--accum_iter 16


# jsiec_in_distribution
CUDA_VISIBLE_DEVICES=0 python train_multiscale_odin.py \
--eval \
--test_name "test" \
--result_root_path "./SLO_results/odin_250609" \
--result_name "jsiec_in_distribution" \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 4 \
--data_path "/data_A/xujialiu/datasets/UWF_external/UWF_DR/UWF_DR_bk_error_name" \
--loss_type "cross_entropy" \
--finetune "/data_A/xujialiu/projects/FMUE_SLO/SLO_results/stdr_bode_250510/stdr_bode_icdr_visionfm_1344_4cls_20250513_1814/checkpoints/checkpoint_38.pth" \
--csv_path "/data_A/xujialiu/datasets/UWF_external/000000_prepare_external_validation/UWF_DR.csv" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 1 \
--accum_iter 16

# jsiec_other_diseases
CUDA_VISIBLE_DEVICES=0 python train_multiscale_odin.py \
--eval \
--test_name "test" \
--result_root_path "./SLO_results/odin_250609" \
--result_name "jsiec_other_diseases" \
--fusion_layer_num 8 \
--model vit_base_patch16_multiscales \
--dataset_type slo \
--clip_grad 1 \
--num_patches "[(6,6), (5,5), (4,4), (3,3), (2,2), (1,1)]" \
--lora_rank 8 \
--lora_alpha 16 \
--blr 1e-3 \
--layer_decay 0.65 \
--drop_path 0.1 \
--epochs 50 \
--random_crop_perc 0.9 \
--nb_classes 4 \
--data_path "/data_A/xujialiu/datasets/UWF_other_diseases/ori" \
--loss_type "cross_entropy" \
--finetune "/data_A/xujialiu/projects/FMUE_SLO/SLO_results/stdr_bode_250510/stdr_bode_icdr_visionfm_1344_4cls_20250513_1814/checkpoints/checkpoint_38.pth" \
--csv_path "/data_A/xujialiu/datasets/UWF_other_diseases/data_test.csv" \
--input_size "[1344,1344]" \
--fm_input_size 224 \
--batch_size 1 \
--accum_iter 16